### PR TITLE
Update benchmark.yml to use `lts` instead of `1.6`.

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Review by evetion — APPROVED** [review]

**Comment by rafaqz** [comment]
Huh
```  
  GDALError (CE_Failure, code 1):
  	OGRFieldDefn::SetDefault() not allowed on a sealed object
```

**Comment by evetion** [comment]
I think some tests are just broken on master, might be a recent gdal release?

**Comment by rafaqz** [comment]
Yes it must be. But looks like some fixing is needed

**Review by yeesian — APPROVED** [review]

**Comment by yeesian** [comment]
Is the failure in https://github.com/yeesian/ArchGDAL.jl/actions/runs/11822349442/job/32939196358?pr=443 expected with this change?

**Comment by evetion** [comment]
> Is the failure in [yeesian/ArchGDAL.jl/actions/runs/11822349442/job/32939196358?pr=443](https://github.com/yeesian/ArchGDAL.jl/actions/runs/11822349442/job/32939196358?pr=443) expected with this change?

I think that's because the latest macos runner has changed infrastructure? Probably best to pin the architecture to x64 (and maybe ubuntu instead of macos?)

**Pull request merged**
