### PR TITLE
bump GDAL version to 1.7

### PR DESCRIPTION
**Pull request by rafaqz**

### CODE REVIEW

**Comment by rafaqz** [comment]
@visr / @yeesian can we get a quick merge on this. I will also fix the registry now for the previous version

**Review by visr — APPROVED** [review]
Thanks! For context, see #425 which was a result of this missing compat in #423.

**Comment by rafaqz** [comment]
The registry fix is here

https://github.com/JuliaRegistries/General/pull/107486

**Comment by visr** [comment]
Sorry I directly triggered a new release, when that is merged in a few minutes, can you update your branch on top of that?

https://github.com/JuliaRegistries/General/pull/107490

**Pull request merged**
