### PR TITLE
Update for latest JuliaGeo/GDAL

### PR DESCRIPTION
**Pull request by yeesian**

### CODE REVIEW

**Comment by visr** [comment]
Should your StringList be updated to match https://github.com/JuliaGeo/GDAL.jl/pull/47/commits/5069a757953e4d07b71fae9c854f6d789a6753f9?

And supposedly some of your at-gdal lib calls can now be replaced with a GDAL.jl function call? Doesn't have to be part of it, but would be nice if you can drop workarounds :)

It curiously fails locally for me, but haven't found the problem yet.
```
ArchGDAL: Error During Test
  Got an exception of type LoadError outside of a @test
  LoadError: GDALError (CE_Failure, code 3):
        VSIFReadL(00000000360018E0,6*4) @ 86498296 failed in HFAEntry().
  No error

  Stacktrace:
   [1] gdaljl_errorhandler(::GDAL.CPLErr, ::Int32, ::Cstring) at C:\Users\visser_mn\.julia\v0.6\GDAL\src\error.jl:26
   [2] #unsafe_read#17(::ArchGDAL.GDALOpenFlag, ::Ptr{Ptr{UInt8}}, ::Ptr{Ptr{UInt8}}, ::Ptr{Ptr{UInt8}}, ::Function, ::String) at C:\Users\visser_mn\.julia\v0.6\ArchGDAL\src\dataset.jl:248
   [3] unsafe_read(::String) at C:\Users\visser_mn\.julia\v0.6\ArchGDAL\src\dataset.jl:248
   [4] #read#92(::Array{Any,1}, ::Function, ::##192#204, ::String, ::Vararg{String,N} where N) at C:\Users\visser_mn\.julia\v0.6\ArchGDAL\src\context.jl:81
   [5] #registerdrivers#39(::Array{Any,1}, ::Array{Any,1}, ::Function, ::##191#203) at C:\Users\visser_mn\.julia\v0.6\ArchGDAL\src\context.jl:21
   [6] registerdrivers(::Function) at C:\Users\visser_mn\.julia\v0.6\ArchGDAL\src\context.jl:5
```

**Comment by yeesian** [comment]
> Even though AppVeyor is green, it does fail this test, but it's just floating point fuzziness. Maybe good to replace it with something less sensitive? The result is different on different platforms.

Which test are you referring to?

**Comment by visr** [comment]
Ah sorry I forgot the link:
https://ci.appveyor.com/project/NgYeeSian/archgdal-jl/build/job/vfuw912r0ke8xkx8#L59
https://github.com/yeesian/ArchGDAL.jl/blob/f25b4701e6e5ab9a496bd9ed4aec04e105ad30e1/test/test_cookbook_geometry.jl#L776

**Comment by visr** [comment]
I'm still getting the `VSIFReadL` error above. At first I thought it was unrelated, but on ArchGDAL master I'm not getting it. AppVeyor doesn't see it though. @evetion, do you get the same error locally on Windows?

**Comment by evetion** [comment]
I'm getting the `AG.toJSON` failing test. But no `VSIFReadL` or any other errors.

**Comment by visr** [comment]
Ok thanks. So lets ignore `VSIFReadL` and attribute it to my pc being wonky for now. If it keeps popping up or I can reproduce elsewhere (or others reading this see it), we can make an issue.

**Comment by yeesian** [comment]
Thanks for the review and fixes!

**Pull request merged**
