### PR TITLE
WIP: Decreasing test size

### PR DESCRIPTION
**Pull request by pritamd47**
As noted in #104, testing ArchGDAL requires around 200MB of datasets to be downloaded.
The objective of this PR is to tackle this issue.

As suggested by @visr [here](https://github.com/yeesian/ArchGDAL.jl/pull/106#issuecomment-617355335) in an earlier [PR](https://github.com/yeesian/ArchGDAL.jl/pull/106#issue-368478017) with the same objective, this PR is much cleaner.

### CODE REVIEW

**Comment by visr** [comment]
Looks good, test are passing :)
Could you remove the lines you have commented out? We can always get them back from git history.

**Comment by visr** [comment]
Great, thanks. What it the reason that you marked it WIP, work in progress? Do you still want to make other changes in this PR, or is this good to go?

**Comment by pritamd47** [comment]
It is good to go now. I used the WIP tag in case I needed to make further changes.

**Comment by visr** [comment]
As long as you think you are done, you can leave it out. Otherwise people may wait for you to finish :)

**Comment by yeesian** [comment]
Many thanks Pritam! :)

**Pull request merged**
