### PR TITLE
[WIP]Update from DataStreams to Tables

### PR DESCRIPTION
**Pull request by Sov-trotter**

### CODE REVIEW

**Comment by visr** [comment]
Great contribution, thanks! Let us know when it's ready for review.

I didn't know NamedTupleTools before, but I see you are using it to simplify namedtuple creation, is that right? If it's just that, I would probably prefer not to take on an extra dependency for that reason.

**Comment by Sov-trotter** [comment]
Thanks for looking into it. I was facing a bit of problem with the types, so hastily used the NamedTupleTools. I also added it so that I can simplify the benchmarks that I talked about. I'll have it sorted out before merging. :)

**Comment by Sov-trotter** [comment]
Reference to the issue #69

**Comment by Sov-trotter** [comment]
Rest of the commits will be made in #117

**Pull request closed without merging**
