### PR TITLE
Support the new Tables interface

### PR DESCRIPTION
**Pull request by Sov-trotter**

### CODE REVIEW

**Comment by Sov-trotter** [comment]
TODO : 
* Add GDAL open options https://gdal.org/drivers/vector/csv.html#open-options 
* https://github.com/yeesian/ArchGDALDatasets/pull/1#issuecomment-674565275

**Comment by Sov-trotter** [comment]
@visr @yeesian  should I add a link to the open options on the GDAL webpage or add all of them in the docs?

**Comment by visr** [comment]
I'd link to the GDAL webpage

**Comment by Sov-trotter** [comment]
@yeesian @visr Is there anything more I can add? :)

**Comment by visr** [comment]
Do you think you could add the doc commits to the branch of #118? Will be easier to keep them together and merge once.

**Comment by Sov-trotter** [comment]
So I branched this PR out of #118, won't it be better to use this and close the other?

**Comment by visr** [comment]
The other one has the past reviews, would prefer to update that one instead.

**Comment by Sov-trotter** [comment]
Oh really sorry, I moved all over here. :(

**Comment by Sov-trotter** [comment]
Merged in #118

**Pull request closed without merging**
