### PR TITLE
Handle non-bijective data-type conversions more robustly

### LINKED ISSUE #232: Handle non-bijective data-type conversions more robustly
Given that we're using dictionaries for the code to convert between data types, there's no good way of [asserting "default type comes last" for mappings that are not bijective](https://github.com/yeesian/ArchGDAL.jl/blob/f4406a55c5e2d42e0617e5e686d87f71d376d4be/src/types.jl#L305-L310).

Opening this ticket to
* Include it in the docstring for the `convert` macro.
* Add unit tests for them.
* Rewrite the implementation to [enforce it by construction](https://discourse.julialang.org/t/initialising-a-dictionary-with-duplicate-keys/2290/2).

### PR DESCRIPTION
**Pull request by mathieu17g**
Fixes #232
Assert "default type comes last" for mappings that are not bijective
- [x] Include it in the docstring for the convert macro
- [x] Add unit tests for them.
- [x] Rewrite the implementation to enforce it by construction

I have enriched the `@convert` macro's docstring with some explanations and added a note on "default type comes last"

---
Before going further, @yeesian could you elaborate on:
>  asserting "default type comes last" for mappings that are not bijective.

Should we enforce it with something like:
1) enhance the readability of the macro call
```julia
@convert(
    OGRFieldType::DataType,
    OFTInteger::(Bool, Int16, Int32, ) # default type comes last
    OFTInteger64::Int64,
)
```
and assert that all type ids of type 1 and all type ids / subtypes of type 2 are unique?

2) Or is it enough to assert that all type id <-> type id / subtype mappings are unique in `args`? 
3) Or something else?

### CODE REVIEW

**Comment by yeesian** [comment]
I think we don't need to enhance the readability of the macro call, since the current one also works in the reverse direction.

I was thinking more about writing https://github.com/yeesian/ArchGDAL.jl/blob/18578bb0d27b3aa0db707c50dfb097aeb69f8765/src/utils.jl#L60-L75 as a loop as suggested in https://discourse.julialang.org/t/initialising-a-dictionary-with-duplicate-keys/2290/2. That way, the behavior is deterministic rather than relying on the current implementation of `Dict` (which could change).

**Review by mathieu17g — COMMENTED** [review]
Tests fails in Julia 1.3 because there were no ImmutableDict method taking a list of Pair arguments. It has been [fixed](https://github.com/JuliaLang/julia/pull/36143#issue-427808934) in Julia 1.6 and back ported to Julia 1.5

I will add a copy of the fix in utils.jl for Julia versions < v"1.5"

**Review by mathieu17g — COMMENTED** [review]
Still does not work, I will fallback to the initial helper constructor based on a loop for Julia version `< v"1.5"`

**Comment by yeesian** [comment]
This is great! Thank you so much (as always)!

**Pull request merged**
