### PR TITLE
fixed test failure in testset "GDAL Colors and Palettes"

### PR DESCRIPTION
**Pull request by ikselven**

### CODE REVIEW

**Comment by visr** [comment]
Thanks. Surprisingly, this fails for me.

This seems fine and in accordance with [GDAL docs](http://gdal.org/gdal_8h.html#ad7b6e4da7a2a8d591fa5bcae16927bef)
```julia
julia> GDAL.GARIO_ERROR
GARIO_ERROR::GDAL.GDALAsyncStatusType = 2

julia> GDAL.GARIO_PENDING
GARIO_PENDING::GDAL.GDALAsyncStatusType = 0
```

This does not seem good. What do you get here, and what GDAL version are you using?
```julia
julia> map(GDAL.getasyncstatustypebyname, ["PENDING", "UPDATE", "ERROR", "COMPLETE", "TypeCount"])
5-element Array{GDAL.GDALAsyncStatusType,1}:
 GARIO_ERROR
 GARIO_UPDATE
 GARIO_ERROR
 GARIO_COMPLETE
 GARIO_ERROR
```

I'm using GDAL 2.2.4, released 2018/03/19

**Comment by ikselven** [comment]
I'm on Arch Linux, using gdal 2.3.0, released on 2018/05/04 (though the package is available in Arch since 2018/05/16).

The first part is the same for me:
```julia
julia> GDAL.GARIO_ERROR                    
GARIO_ERROR::GDAL.GDALAsyncStatusType = 2  
                                           
julia> GDAL.GARIO_PENDING                  
GARIO_PENDING::GDAL.GDALAsyncStatusType = 0
```

But running `map` function you posted returns the following:
```julia
julia> map(GDAL.getasyncstatustypebyname, ["PENDING", "UPDATE", "ERROR", "COMPLETE", "TypeCount"])
5-element Array{GDAL.GDALAsyncStatusType,1}:                                                      
 GARIO_PENDING                                                                                    
 GARIO_UPDATE                                                                                     
 GARIO_ERROR                                                                                      
 GARIO_COMPLETE                                                                                   
 GARIO_ERROR                                                                                      
```

**Comment by visr** [comment]
Ok I hope that this is just something that is fixed on GDAL 2.3 in general.

Soon we will likely all use the same GDAL version after this is merged: https://github.com/visr/GDAL.jl/pull/46

Once that is working I also want to update GDAL.jl for 2.3.
@yeesian shall we just merge this now, or do you prefer to disable the test until we are all on 2.3?

**Comment by yeesian** [comment]
Thanks Felix! I see no reason to disable and then re-enable the test; it shouldn't affect the qualitative experience of users of the package.

**Pull request merged**
